version: '3.5'

services:
  angular-service: 
    container_name: angular-container2
    build: ./
    volumes: 
    - ./:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "4202:80"
    command: >
      bash -c "npm start"
  docker-nginx:
    container_name: docker-nginx
    build: ./
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    links:
      - angular-service
   
